#!/bin/bash

# wrzuc do etc/NetworkManager/dispatcher.d/99-nextdns-restart

INTERFACE=$1
ACTION=$2

# Reagujemy tylko, gdy sieć faktycznie wstaje (up)
if [ "$ACTION" = "up" ]; then
    # Czekamy 2 sekundy, aż system dogada się z routerem na dobre
    sleep 5
    /usr/bin/systemctl restart nextdns
    /usr/bin/nextdns activate
    /usr/bin/curl -s "https://link-ip.nextdns.io/89bd6a/d026f4ee8b51832d"
fi
