#!/bin/bash

####################
#
#
#	systemd sleep hook - xsecurelock blokuje OS PRZED suspendem 
#	wrzucaj do /usr/lib/systemd/system-sleep/
#   trablszót - journalctl -u systemd-suspend i szukaj timed outkilling
#
###################

logger "LockScreen hook: $1"

case "$1" in
    pre)
        logger "LockScreen hook: startuje xsecurelock..."
        
        # Uruchom bez '&' na końcu, jeśli chcesz, by systemd poczekał na koniec skryptu
        # Ale uwaga: jeśli xsecurelock nie wyjdzie (a nie wyjdzie, bo blokuje), 
        # systemd może zabić skrypt po upływie timeoutu.
        
        sudo -u f3t1 DISPLAY=:0 XAUTHORITY=/home/f3t1/.Xauthority /home/f3t1/.config/lock_screen.sh &
        
        # srawdzam czy xsecurelock faktycznie "trzyma" ekran
        # To zapobiega sytuacji, w której sleep mija, a blokada nie działa
        # gdy "przepuszcza", zwiększ MAX_RETRIES do 50, a sleep zostaw na 0.1 lub 0.2
        MAX_RETRIES=20
        COUNT=0
        while ! xwininfo -root -tree | grep -q "xsecurelock" && [ $COUNT -lt $MAX_RETRIES ]; do
            sleep 0.1
            ((COUNT++))
        done
        
        logger "LockScreen hook: Blokada potwierdzona po $COUNT próbach."
        ;;
esac
